export {
  TeamGagaMiniApp,
  createMiniAppSDK,
  getTgg,
  getCommunityId,
  getCommunityInfo,
  getOauthCode,
  getSystemInfo,
  getUserId,
  getUserInfo,
  onContentSafeAreaChanged,
  onSafeAreaChanged,
  onThemeChanged,
  onViewportChanged,
  setHeaderColor,
  tgg,
} from "./sdk";

export { createTggRuntime, getSupportedCapabilities, installTggRuntime } from "./core-runtime";

export { tgg as default } from "./sdk";

export type {
  BridgeTransport,
  ClipboardTextReceivedCallback,
  ClipboardTextReceivedResult,
  ContentSafeAreaChangedCallback,
  FlutterInAppWebViewBridge,
  CapabilityConfig,
  CommunityInfo,
  DownloadFileCompleteResult,
  DownloadFileFailResult,
  DownloadFileOptions,
  DownloadFileSuccessResult,
  DownloadProgress,
  DownloadTask,
  DownloadTaskCallback,
  InitData,
  LaunchContext,
  MiniAppInvokeRequest,
  MiniAppInvokeResponse,
  MiniAppMethod,
  MiniAppNativeError,
  MiniAppSDK,
  MiniAppSDKError,
  MiniAppSDKOptions,
  SafeAreaInset,
  SafeAreaChangedCallback,
  SavePhotoOptions,
  SaveVideoOptions,
  SystemInfo,
  ThemeChangedCallback,
  ThemeChangedPayload,
  ThemeParams,
  UserInfo,
  TggBackButton,
  TggCapability,
  TggColorScheme,
  TggEventName,
  TggEventPayload,
  TggHeaderColor,
  TggRuntimeOptions,
  TggWebApp,
  ViewportChangedCallback,
  ViewportChangedPayload,
  WebViewFlutterJavaScriptChannel,
} from "./types";
