export {
  TeamGagaMiniApp,
  createMiniAppSDK,
  getTgg,
  getCommunityId,
  getCommunityInfo,
  getOauthCode,
  getSystemInfo,
  getUserId,
  getUserInfo,
  setHeaderColor,
  tgg,
} from "./sdk";

export { createTggRuntime, getSupportedCapabilities, installTggRuntime } from "./core-runtime";

export { tgg as default } from "./sdk";

export type {
  BridgeTransport,
  ClipboardTextReceivedCallback,
  ClipboardTextReceivedResult,
  FlutterInAppWebViewBridge,
  CapabilityConfig,
  CommunityInfo,
  DownloadFileCompleteResult,
  DownloadFileFailResult,
  DownloadFileOptions,
  DownloadFileSuccessResult,
  DownloadProgress,
  DownloadTask,
  DownloadTaskCallback,
  InitData,
  LaunchContext,
  MiniAppInvokeRequest,
  MiniAppInvokeResponse,
  MiniAppMethod,
  MiniAppNativeError,
  MiniAppSDK,
  MiniAppSDKError,
  MiniAppSDKOptions,
  SaveImageToAlbumOptions,
  SystemInfo,
  UserInfo,
  TggBackButton,
  TggCapability,
  TggColorScheme,
  TggEventName,
  TggEventPayload,
  TggHeaderColor,
  TggRuntimeOptions,
  TggWebApp,
  WebViewFlutterJavaScriptChannel,
} from "./types";
